---
version: '3.8'
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    networks:
      - redis

  rq-dashboard:
    image: eoranged/rq-dashboard
    ports:
      - '9181:9181'
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://kroket-stream-relay_redis_1:6379
    networks:
      - redis

  postgres:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kroket
    volumes:
    # Enable if data is already present in local machine
    #  - './DB_DATA:/var/lib/postgresql/data'
    # Enable to automatically load sql backup. Beware: Changes will not be saved.
      - './db_demo.sql:/docker-entrypoint-initdb.d/db.sql'
    ports:
      - '5432:5432'
    networks:
      - redis

  api:
    image: node:16.13.1-alpine
    build: ./backend
    volumes:
      - './STREAMS_DATA:/app/public/'
    ports:
      - '3001:3001'
    depends_on:
      - redis
    networks:
      - redis

  ingest:
    build:
        context: ./backend
        dockerfile: Dockerfile-ingest
    image: ingest
    volumes:
      - './STREAMS_DATA:/app/public'
    depends_on:
        - redis
    restart: always
    deploy:
        replicas: 1
    networks:
        - redis

  relay:
    build:
        context: ./backend
        dockerfile: Dockerfile-relay
    image: relay
    volumes:
      - './STREAMS_DATA:/app/public'
    depends_on:
        - redis
    restart: always
    deploy:
        replicas: 1
    networks:
        - redis
  
  thumbnails:
    build:
        context: ./backend
        dockerfile: Dockerfile-thumbnails
    image: thumbnails
    volumes:
      - './STREAMS_DATA:/app/public'
    depends_on:
        - redis
    restart: always
    deploy:
        replicas: 1
    networks:
        - redis

  frontend:
    build:
        context: ./frontend
    image: frontend
    environment:
      REACT_APP_API_SERVER: 'http://localhost:3001'
    restart: always
    ports:
      - '80:80'

networks:
  redis:
    name: redis
