---
version: '3.8'
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    networks:
      - redis

  rq-dashboard:
    image: eoranged/rq-dashboard
    ports:
      - '9181:9181'
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://kroket-stream-relay_redis_1:6379
    networks:
      - redis

networks:
  redis:
    external: true
    name: redis
