---
version: '3.8'
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    networks:
      - redis

  rq-dashboard:
    image: eoranged/rq-dashboard
    ports:
      - '9181:9181'
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://kroket-stream-relay_redis_1:6379
    networks:
      - redis

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - './DB_DATA:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  api:
    image: node:16.13.1-alpine
    build: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - redis
    networks:
      - redis

  ingest:
    build:
        context: ./backend
        dockerfile: Dockerfile-ingest
    image: ingest
    depends_on:
        - redis
    restart: always
    deploy:
        replicas: 3
    networks:
        - redis

  frontend:
    build:
        context: ./frontend
    image: frontend
    restart: always
    ports:
      - '80:80'

networks:
  redis:
    external: true
    name: redis
