---
version: '3.8'
services:
  api:
    image: registry.arturobracero.com/square/kroket-stream-relay-api:${TAG}

  ingest:
    image: registry.arturobracero.com/square/kroket-stream-relay-ingest:${TAG}

  relay:
    image: registry.arturobracero.com/square/kroket-stream-relay-relay:${TAG}

  thumbnails:
    image: registry.arturobracero.com/square/kroket-stream-relay-thumbnails:${TAG}

  frontend:
    environment:
      NODE_ENV: production
    image: registry.arturobracero.com/square/kroket-stream-relay-frontend:${TAG}
