FROM node:16.13.1-alpine

USER root

# Install Python and pip
RUN apk add --update python3 python3-dev py3-pip

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt --ignore-installed

# Copy only package files as user node
COPY --chown=node:node package*.json ./

# Use node user so it's not run as root
USER node

# Install production libraries
RUN npm i

# Set copy app files as user node
COPY --chown=node:node . .

EXPOSE 3001

WORKDIR /app/tasks

ENTRYPOINT ["rq", "worker", "ingest", "--exception-handler", "'errorHandlers.ingest_error_handler'"]