# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Test Backend
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/Checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
      - run: npm ci
      - run: npm test

  # This workflow contains a single job called "build"
  build:
    # Only build and upload to Dockerhub if tests pass
    needs: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: karratu/kroket-stream-relay:api

      - name: Build and push Ingest
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile-ingest
          push: true
          tags: karratu/kroket-stream-relay:ingest

      - name: Build and push Relay
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile-relay
          push: true
          tags: karratu/kroket-stream-relay:relay

      - name: Build and push Thumbnails
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile-thumbnails
          push: true
          tags: karratu/kroket-stream-relay:thumbnails

      - name: Create env file for frontend
        run: |
          touch ./frontend/.env
          echo REACT_APP_API_SERVER=${{ secrets.REACT_APP_API_SERVER }} >> .env
          cat .env

      - name: Build and push Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: karratu/kroket-stream-relay:frontend
